# Generated by Django 5.2.7 on 2025-10-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VENDORS', 'vendors'), ('customer', 'CUSTOMER')], max_length=10),
        ),
    ]
