# Generated by Django 5.2.7 on 2025-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_order_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VENDORS', 'VENDORS'), ('CUSTOMER', 'Customer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
